name: build
on: [push, pull_request]

jobs:
  iso_build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Install requirement
        run: |
          pacman -Sy
          pacman -S archiso --noconfirm